// This file defines the root layout for the entire Next.js application.
// It wraps all pages and provides a consistent structure, including global styles and fonts.

// Import necessary font functions from Next.js.
// These are used to optimize and load custom fonts for the application.
import { Geist, Geist_Mono } from "next/font/google";

// Import global CSS styles. These styles apply across the entire application.
import "./globals.css";

// Configure the Geist Sans font.
// 'variable' makes the font available as a CSS variable for easy styling.
// 'subsets' specifies which character sets to load (e.g., Latin characters).
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configure the Geist Mono font, similar to Geist Sans.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata for the application.
// This metadata is used by search engines and browsers (e.g., for page title in browser tabs).
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the RootLayout component.
// This component receives 'children' as a prop, which represents the content of the current page.
export default function RootLayout({ children }) {
  return (
    // The root HTML structure for the application.
    <html lang="en">
      {/* The body of the HTML document. */}
      {/* Font variables are applied here for consistent typography across the app. */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Render the content of the current page here. */}
        {children}
      </body>
    </html>
  );
}
